usage:
  rules:
    - selector: /eps4g.ping.PingService/Send
      allow_unregistered_calls: true

    - selector: /esp4g.calc.CalcService/AddAll
      allow_unregistered_calls: true

    - selector: /esp4g.calc.CalcService/AddDeffered
      allow_unregistered_calls: true
