logs:
  logging: true
  prometheus:
    enable: true
    address: ":8080"
    response_time_histogram:
      name: "grpc_response_time_seconds"
      help: "gRPC latency distributions."
      buckets: [0.001, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10]

usage:
  rules:
    - selector: "/esp4g.calc.CalcService/AddAsync"
      allow_unregistered_calls: true

    - selector: "/esp4g.calc.CalcService/AddAll"
      registered_api_keys:
        - guest

    - selector: "/esp4g.calc.CalcService/AddDeffered"
