logs:
  logging: true
  prometheus:
    port: 8080
    histograms:
      response_seconds:
        name: "grpc_response_seconds"
        help: "gRPC latency distributions."
        buckets: [0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008, 0.009, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10]
      request_bytes:
        name: "grpc_request_bytes"
        help: "gRPC request content size distributions."
        buckets: [1, 2, 4, 8, 16, 32, 64, 128]
      response_bytes:
        name: "grpc_response_bytes"
        help: "gRPC response content size distributions."
        buckets: [1, 2, 4, 8, 16, 32, 64, 128]

usage:
  rules:
    - selector: "/esp4g.benchmark.UnaryService/Send"
      allow_unregistered_calls: true

    - selector: "/eps4g.ping.PingService/Send"
      allow_unregistered_calls: true

    - selector: "/esp4g.calc.CalcService/AddAsync"
      allow_unregistered_calls: true

    - selector: "/esp4g.calc.CalcService/AddAll"
      allow_unregistered_calls: true

    - selector: "/esp4g.calc.CalcService/AddDeffered"
      allow_unregistered_calls: true
